# use java support
language: java
jdk: openjdk11

# run in container
sudo: false

# use linux as operating system
os: linux
dist: xenial

# configure xvfb screen
services:
  - xvfb

# Do not run travis install step
install: true

# Assemble jars
script:
  - mvn clean compile verify

cache:
  directories:
    - $HOME/.m2

deploy:
  # Deploy snapshots on every commit made to master
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -DskipTests=true -Dgpg.skip"
    skip_cleanup: true
    on:
      branch: master

  # Deploy releases on every tag push
  - provider: script
    script: sh .ci/release.sh
    skip_cleanup: true
    on:
      tags: true